---
- name: Deploy new OSPF configurations
  hosts: OSPF-SINGLE-AREA
  gather_facts: false
  tasks:
    - name: Assign new OSPF configs
      cisco.ios.ios_config:
        lines: "{{ lookup('template', 'ospf_config.j2') }}"
      vars:
        ospf_process: '{{ ospf_processes[0] }}'
